### ISSUE TITLE
I can't Find first Parent element by use IUIAutomationElement.FindFirst()  or IUIAutomationElement3.FindFirst() .. and so on

### ISSUE THREAD

**Issue by ym9288** [Roemer/UIAutomation-Interop#1]
At first:   I created a CUIAutomationClass or CUIAutomation8Class instance and cacheRequest
```
            uia = new CUIAutomationClass();
           cacheRequest = AutomationHelper.UIA.CreateCacheRequest();
            cacheRequest.AddProperty(UIA_PropertyIds.UIA_ClassNamePropertyId);
            cacheRequest.AddProperty(UIA_PropertyIds.UIA_NamePropertyId);
            cacheRequest.AddProperty(UIA_PropertyIds.UIA_ControlTypePropertyId);
            cacheRequest.AddProperty(UIA_PropertyIds.UIA_ProcessIdPropertyId);
            cacheRequest.AddProperty(UIA_PropertyIds.UIA_BoundingRectanglePropertyId);
            cacheRequest.TreeScope = TreeScope.TreeScope_Element;
```
Second:  I get a element from Desktop MousePoint
```
           User32.GetCursorPos(out POINT point))                
           element = uia.ElementFromPointBuildCache(new tagPOINT { x = point.X, y = point.Y }, cacheRequest);
```
Tips：right now ,the element is a Notpad.exe's " Edit Area"
Then: here is the problem coming....
        I want to get the parent of the element, so I code like this:
```
        var res = element.FindFirst(TreeScope.TreeScope_Parent,AutomationHelper.UIA.ControlViewCondition);
```
   The res  is always null event through I Change to TreeScope.TreeScope_Ancestors, niether convert the element to IUIAutomationElement3 too.

SomeBody who knows ?  
                                                                                   Thanks all

**Comment by ym9288** [comment]
Thanks God !
 I jsut Use CUIAutomationClass .ControlViewWalker.GetParentElement instead  successfuly got the parent.

**Comment by Roemer** [comment]
Ok so there are a few issues:
First you are building a cache in the scope of the element, so the parent is not in the cacheRequest. You should adjust the `TreeScope` accordingly (at least to Element | Parent).
Second to get the parent, I think there is a `GetCachedParent` method on the element you should use. The one you're now using is not using a cached parent but getting a fresh parent from a cached element which can be undesired.

**Comment by ym9288** [comment]
> Ok so there are a few issues:
> First you are building a cache in the scope of the element, so the parent is not in the cacheRequest. You should adjust the `TreeScope` accordingly (at least to Element | Parent).
> Second to get the parent, I think there is a `GetCachedParent` method on the element you should use. The one you're now using is not using a cached parent but getting a fresh parent from a cached element which can be undesired.

So I use this:
cacheRequest.TreeScope = TreeScope.TreeScope_Element | TreeScope.TreeScope_Parent;
But it goes wrong by runtime exception Type:TypeInitializationException.
It seems like CacheRequest can  accept just only one TreeScope type.

**Comment by ym9288** [comment]
> accordingly
event through use just one of  "Ancestors Parent "
"cacheRequest.TreeScope = TreeScope.TreeScope_Parent"  or "cacheRequest.TreeScope = TreeScope.TreeScope_Ancestors "
They all goes wrong by runtime exception Type:TypeInitializationException.

**Comment by Roemer** [comment]
I just saw at https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-cachingforclients#specifying-the-scoping-and-filtering-of-a-caching-request that in cache requests, `You cannot cache parents or ancestors of the root element of the request.`
So this won't work. You need to get the parent for example with the tree walker:
```
var tw = uia.CreateTreeWalker(uia.CreateTrueCondition());
var parent = tw.GetParentElement(element);
```

**Comment by ym9288** [comment]
> I just saw at https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-cachingforclients#specifying-the-scoping-and-filtering-of-a-caching-request that in cache requests, `You cannot cache parents or ancestors of the root element of the request.`
> So this won't work. You need to get the parent for example with the tree walker:
> 
> ```
> var tw = uia.CreateTreeWalker(uia.CreateTrueCondition());
> var parent = tw.GetParentElement(element);
> ```

That's good ,Thanks for your help!
