### ISSUE TITLE
CUIAutomation8Class.ElementFromPointBuildCache(....)  throw out a  UnauthorizedAccessException

### ISSUE THREAD

**Issue by ym9288** [Roemer/UIAutomation-Interop#2]
I started a Win32 App, and it can be found by use inspect.exe.
but when I access it in my C# code by use CUIAutomation8Class.ElementFromPointBuildCache([this is screen point]),
It throw me a UnauthorizedAccessException,
 Anybody know the reason?

**Comment by Roemer** [comment]
You maybe need to run your c# code elevated when the win32 app also has extended rights.

**Comment by ym9288** [comment]
> You maybe need to run your c# code elevated when the win32 app also has extended rights

 I Got it, works well when run as Admin.
  Thank U
